name: "Notion backup"

on:
  workflow_dispatch:
  schedule:
      - cron: "7 1 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run backup & commit
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bash backup.sh
